name: bde
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.14.2
  - duckdb-engine=0.15.0
  - fastavro=1.12.1
  - google-cloud-storage=3.4.1
  - grpcio=1.71.0
  - grpcio-tools=1.71.0
  - ipykernel=6.31.0
  - matplotlib=3.10.7
  - pandas=2.3.3
  - pip=25.3
  - pyarrow=21.0.0
  - pymongo=4.15.4
  - pytest=8.4.2
  - python=3.11.14
  - python-dotenv=1.1.0
  - python-duckdb=1.2.1
  - python-snappy=0.7.3
  - redis-py=7.0.1
  - requests=2.32.5
  - sqlalchemy=2.0.43
  - thriftpy2=0.5.3
prefix: /home/ds3/miniconda3/envs/bde
