name: dagster2
channels:
  - defaults
dependencies:
  - aom=3.12.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libiconv=1.16
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pycparser=2.23
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tornado=6.5.4
  - tzdata=2025b
  - urllib3=2.6.1
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - agate==1.9.1
      - alembic==1.17.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.12.0
      - attrs==25.4.0
      - babel==2.17.0
      - backoff==2.2.1
      - cachetools==6.2.4
      - check-jsonschema==0.35.0
      - click==8.3.1
      - click-default-group==1.2.4
      - colorama==0.4.6
      - coloredlogs==14.0
      - daff==1.4.2
      - dagster==1.12.8
      - dagster-dbt==0.28.8
      - dagster-duckdb==0.28.8
      - dagster-duckdb-pandas==0.28.8
      - dagster-graphql==1.12.8
      - dagster-pipes==1.12.8
      - dagster-shared==1.12.8
      - dagster-webserver==1.12.8
      - dateparser==1.2.2
      - db-dtypes==1.5.0
      - dbt-adapters==1.22.2
      - dbt-bigquery==1.11.0
      - dbt-common==1.37.2
      - dbt-core==1.10.17
      - dbt-extractor==0.6.0
      - dbt-protos==1.0.410
      - dbt-semantic-interfaces==0.9.0
      - deepdiff==8.6.1
      - distlib==0.4.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - duckdb==1.4.3
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - filelock==3.20.2
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-api-core==2.28.1
      - google-auth==2.45.0
      - google-auth-oauthlib==1.2.2
      - google-cloud-aiplatform==1.132.0
      - google-cloud-bigquery==3.39.0
      - google-cloud-core==2.5.0
      - google-cloud-dataproc==5.23.0
      - google-cloud-resource-manager==1.15.0
      - google-cloud-storage==3.1.1
      - google-crc32c==1.8.0
      - google-genai==1.56.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - gql==4.0.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - grpc-google-iam-v1==0.14.3
      - grpcio==1.76.0
      - grpcio-health-checking==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - humanfriendly==10.0
      - importlib-metadata==8.7.1
      - isodate==0.7.2
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - leather==0.4.1
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mashumaro==3.14
      - mdurl==0.1.2
      - meltano==4.0.8
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - nbformat==5.10.4
      - networkx==3.6.1
      - oauthlib==3.3.1
      - orderly-set==5.5.0
      - orjson==3.11.5
      - pandas-gbq==0.32.0
      - parsedatetime==2.6
      - pathlib-abc==0.5.2
      - pathspec==0.12.1
      - platformdirs==4.5.1
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.2
      - psutil==7.2.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydata-google-auth==1.9.1
      - pygments==2.19.2
      - python-dotenv==1.2.1
      - python-slugify==8.0.4
      - pytimeparse==1.1.8
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - regress==2025.10.1
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - shapely==2.1.2
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowplow-tracker==1.1.0
      - sqlalchemy==2.0.45
      - sqlglot==28.0.0
      - sqlglotrs==0.7.3
      - sqlparse==0.5.4
      - starlette==0.50.0
      - structlog==25.5.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - text-unidecode==1.3
      - tomli==2.3.0
      - tomlkit==0.13.3
      - toposort==1.10
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - universal-pathlib==0.3.7
      - uv==0.9.21
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - virtualenv==20.35.4
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - websockets==15.0.1
      - wrapt==2.0.1
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /Users/ds0/miniconda3/envs/dagster2
