name: dagster2
channels:
  - defaults
dependencies:
  - matplotlib=3.10.7
  - pandas=2.3.3
  - pip=25.3
  - python=3.11.14
  - requests=2.32.5
  - pip:
      - dagster==1.12.7
      - dagster-dbt==0.28.7
      - dagster-duckdb==0.28.7
      - dagster-duckdb-pandas==0.28.7
      - dagster-meltano==1.5.5
      - dagster-webserver==1.12.7
      - dbt-bigquery==1.11.0
      - dbt-core==1.10.17
      - duckdb==1.4.3
      - meltano==4.0.8
      - python-dotenv==1.2.1
prefix: /home/ds1/miniconda3/envs/dagster2
