name: elt
channels:
  - defaults
  - conda-forge
dependencies:
  - dbt-bigquery=1.10.3
  - great-expectations=1.8.0
  - ipykernel=7.1.0
  - matplotlib=3.10.7
  - pandas=2.3.3
  - pip=25.3
  - pytest=8.4.2
  - python=3.11.14
  - python-dotenv=1.1.0
  - requests=2.32.5
  - pip:
      - meltano==4.0.8
prefix: /home/ds2/miniconda3/envs/elt
