name: ooc3
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=7.1.0
  - pip=25.3
  - python=3.11.14
  - requests=2.32.5
  - pip:
      - duckdb==1.4.3
      - matplotlib==3.10.8
      - pandas==2.3.3
      - polars==1.36.1
      - pyarrow==22.0.0
      - seaborn==0.13.2
prefix: /Users/ds1/miniconda3/envs/ooc3